server:
  port: 8080
  servlet:
    context-path: /demo

spring:
  application:
    name: spring-boot-demo
  profiles:
    active: local

# 指定目录输入 debug
logging:
  level:
    com:
      example:
        springbootdemo:
          outer: debug