server:
  port: 8080
  servlet:
    context-path: /demo

spring:
  application:
    name: spring-boot-demo
  jackson:
    date-format: java.text.SimpleDateFormat


# feign 调用日志设置为 debug，打印调用详细
logging:
  level:
    com:
      example:
        springbootdemo:
          outer: debug
