server:
  port: 8080
  servlet:
    context-path: /demo

spring:
  application:
    name: spring-boot-demo

feign:
  client:
    config:
      default:
        encoder: feign.jackson.JacksonEncoder
        decoder: feign.jackson.JacksonDecoder
        logger-level: basic
