sign:
  configs:
    jsonplaceholder-typicode-com: 123456

# https://springdoc.org/#properties
springdoc:
  api-docs:
    enabled: true

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/my_test
    username: root
    password: 123456
  jpa:
    show-sql: true